//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInfo
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public bool Gender { get; set; }
        public string Position { get; set; }
        public string Department { get; set; }
        public System.DateTime EmployedFrom { get; set; }
        public Nullable<System.DateTime> EmployedTo { get; set; }
        public string LeaveReason { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string ZIP { get; set; }
        public string Place { get; set; }
        public string CountryCode { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
