//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UsersInfoes = new HashSet<UsersInfo>();
        }
        public int UserId { get; set; }
        [Required(ErrorMessage = "Please enter user name"), MaxLength(20)]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Please enter email address"), MaxLength(50)]
        [EmailAddress(ErrorMessage = "Please eneter an email correctly")]
        [RegularExpression("^[a-zA-Z0-9_.-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+$", ErrorMessage = "Must be a valid email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter company name"), MaxLength(30)]
        public string CompanyName { get; set; }
        [Required(ErrorMessage = "Please enter phone number"), MaxLength(20)]
        [Phone(ErrorMessage = "Phone number should have a correct format")]
        public string ContactNo { get; set; }
        [Required(ErrorMessage = "Password is required")]
        [StringLength(255, ErrorMessage = "Must be between 5 and 255 characters", MinimumLength = 5)]
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersInfo> UsersInfoes { get; set; }
    }
}
